### PR TITLE
PMM-5645 go 1.14

### PR DESCRIPTION
**Pull request by askomorokhov**
https://jira.percona.com/browse/PMM-5645

FB: https://github.com/Percona-Lab/pmm-submodules/pull/910

API: https://github.com/percona/pmm/pull/540

### CODE REVIEW

**Comment by AlekSi** [comment]
Do we still need a fork given that https://github.com/go-openapi/spec/pull/116 is merged?

**Comment by askomorokhov** [comment]
> Do we still need a fork given that go-openapi#116 is merged?

I'll check.

**Comment by askomorokhov** [comment]
> Do we still need a fork given that go-openapi#116 is merged?

@AlekSi, yes, we still need it. https://github.com/go-openapi/spec/pull/116 - does not keep all orders, for example, it does not keep in order response for /v1/management/MySQL/Add.

**Review by AlekSi — APPROVED** [review]
I'm not sure if it is a good idea to merge with unreleased version (https://github.com/go-openapi/spec/compare/v0.19.8...master). @BupycHuk PTAL

**Comment by BupycHuk** [comment]
@askomorokhov are these commits related to x-order useful for us? otherwise it's better to use 0.19.8 tag as base for new tag 0.19.8-percona like we did for 0.19.4-percona.

**Pull request closed without merging**
